import LoginPage from '@/app/login/login-page'
import { createFileRoute } from '@tanstack/react-router' //<-- React Router

export const Route = createFileRoute('/_auth/auth/login')({
  //custom lazy route generated by tanstack router.
  component: RouteComponent,
})

function RouteComponent() {
  //<-- what the route contains.
  return <LoginPage />
}
